export const MATH_NOTATION = [
    {
        display: '\\Box^{2}',
        latex: 'x^{2}'
    },
    {
        display: '\\sqrt{\\Box}',
        latex: '\\sqrt{x}'
    },
    {
        display: '\\sqrt[\\Box]{\\Box}',
        latex: '\\sqrt[n]{x}'
    },
    {
        display: '\\frac{\\Box}{\\Box}',
        latex: '\\frac{x}{y}'
    },
    {
        display: '\\Box_{123}',
        latex: 'x_{123}'
    },
    {
        display: '\\leq',
        latex: '\\leq'
    },
    {
        display: '\\geq',
        latex: '\\geq'
    },
    {
        display: '\\neq',
        latex: '\\neq'
    },
    {
        display: '\\pi',
        latex: '\\pi'
    },
    {
        display: '\\alpha',
        latex: '\\alpha'
    },
    {
        display: '\\beta',
        latex: '\\beta'
    },
    {
        display: '\\left \\{ {{\\Box=2} \\atop {\\Box=2}} \\right.',
        latex: '\\left \\{ {{y=2} \\atop {x=2}} \\right.'
    },
    {
        display: '\\int\\limits^\\Box_\\Box {x} \\, dx',
        latex: '\\int\\limits^a_b {x} \\, dx'
    },
    {
        display: '\\lim_{\\Box \\to \\infty} a_\\Box',
        latex: '\\lim_{n \\to \\infty} a_n'
    },
    {
        display:
            '\\left[\\begin{array}{ccc}\\Box&\\Box&\\Box\\\\\\Box&\\Box&\\Box\\\\\\Box&\\Box&\\Box\\end{array}\\right]',
        latex: '\\left[\\begin{array}{ccc}1&2&3\\\\4&5&6\\\\7&8&9\\end{array}\\right]'
    }
];

export const SYMBOL = {
    matematika: [
        { display: '²', value: '²' },
        { display: '³', value: '³' },
        { display: '√', value: '√' },
        { display: '∛', value: '∛' },
        { display: '·', value: '·' },
        { display: '×', value: '×' },
        { display: '÷', value: '÷' },
        { display: '±', value: '±' },
        { display: '≈', value: '≈' },
        { display: '≠', value: '≠' },
        { display: '≤', value: '≤' },
        { display: '≥', value: '≥' },
        { display: '≡', value: '≡' },
        { display: '≅', value: '≅' },
        { display: '⇒', value: '⇒' },
        { display: ',', value: ',' },
        { display: '⇔', value: '⇔' },
        { display: '∈', value: '∈' },
        { display: '∉', value: '∉' },
        { display: '∧', value: '∧' },
        { display: '∨', value: '∨' },
        { display: '∞', value: '∞' },
        { display: 'α', value: 'α' },
        { display: 'β', value: 'β' },
        { display: 'Δ', value: 'Δ' },
        { display: 'π', value: 'π' },
        { display: 'Ф', value: 'Ф' },
        { display: 'ω', value: 'ω' },
        { display: '↑', value: '↑' },
        { display: '↓', value: '↓' },
        { display: '∵', value: '∵' },
        { display: '∴', value: '∴' },
        { display: '↔', value: '↔' },
        { display: '→', value: '→' },
        { display: '←', value: '←' },
        { display: '⇵', value: '⇵' },
        { display: '⇅', value: '⇅' },
        { display: '⇄', value: '⇄' },
        { display: '⇆', value: '⇆' },
        { display: '∫', value: '∫' },
        { display: '∑', value: '∑' },
        { display: '⊂', value: '⊂' },
        { display: '⊃', value: '⊃' },
        { display: '⊆', value: '⊆' },
        { display: '⊇', value: '⊇' },
        { display: '⊄', value: '⊄' },
        { display: '⊅', value: '⊅' },
        { display: '∀', value: '∀' },
        { display: '°', value: '°' },
        { display: '∠', value: '∠' },
        { display: '∡', value: '∡' },
        { display: '⊥', value: '⊥' },
        { display: '∪', value: '∪' },
        { display: '∩', value: '∩' },
        { display: '∅', value: '∅' },
        { display: '¬', value: '¬' },
        { display: '⊕', value: '⊕' },
        { display: '║', value: '║' },
        { display: '∦', value: '∦' },
        { display: '∝', value: '∝' },
        { display: '∞', value: '∞' },
        { display: '㏒', value: '㏒' },
        { display: '㏑', value: '㏑' }
    ],
    supersub: [
        { display: '₁', value: '₁' },
        { display: '₂', value: '₂' },
        { display: '₃', value: '₃' },
        { display: '₄', value: '₄' },
        { display: '₅', value: '₅' },
        { display: '₆', value: '₆' },
        { display: '₇', value: '₇' },
        { display: '₈', value: '₈' },
        { display: '₉', value: '₉' },
        { display: '₀', value: '₀' },
        { display: '₊', value: '₊' },
        { display: '₋', value: '₋' },
        { display: '₍', value: '₍' },
        { display: '₎', value: '₎' },
        { display: 'ₐ', value: 'ₐ' },
        { display: 'ₓ', value: 'ₓ' },
        { display: 'ₙ', value: 'ₙ' },
        { display: '¹', value: '¹' },
        { display: '²', value: '²' },
        { display: '³', value: '³' },
        { display: '⁴', value: '⁴' },
        { display: '⁵', value: '⁵' },
        { display: '⁶', value: '⁶' },
        { display: '⁷', value: '⁷' },
        { display: '⁸', value: '⁸' },
        { display: '⁹', value: '⁹' },
        { display: '⁰', value: '⁰' },
        { display: '⁺', value: '⁺' },
        { display: '⁻', value: '⁻' },
        { display: '°', value: '°' },
        { display: '⁽', value: '⁽' },
        { display: '⁾', value: '⁾' },
        { display: 'ᵃ', value: 'ᵃ' },
        { display: 'ᵇ', value: 'ᵇ' },
        { display: 'ⁿ', value: 'ⁿ' },
        { display: 'ˣ', value: 'ˣ' }
    ],
    sirilik: [
        { display: 'А', value: 'А' },
        { display: 'Б', value: 'Б' },
        { display: 'В', value: 'В' },
        { display: 'Г', value: 'Г' },
        { display: 'Д', value: 'Д' },
        { display: 'Е', value: 'Е' },
        { display: 'Ж', value: 'Ж' },
        { display: 'З', value: 'З' },
        { display: 'Ё', value: 'Ё' },
        { display: 'И', value: 'И' },
        { display: 'Й', value: 'Й' },
        { display: 'К', value: 'К' },
        { display: 'Л', value: 'Л' },
        { display: 'М', value: 'М' },
        { display: 'Н', value: 'Н' },
        { display: 'О', value: 'О' },
        { display: 'П', value: 'П' },
        { display: 'Р', value: 'Р' },
        { display: 'С', value: 'С' },
        { display: 'Т', value: 'Т' },
        { display: 'У', value: 'У' },
        { display: 'Ф', value: 'Ф' },
        { display: 'Х', value: 'Х' },
        { display: 'Ц', value: 'Ц' },
        { display: 'Ч', value: 'Ч' },
        { display: 'Ш', value: 'Ш' },
        { display: 'Щ', value: 'Щ' },
        { display: 'Ъ', value: 'Ъ' },
        { display: 'Ы', value: 'Ы' },
        { display: 'Ь', value: 'Ь' },
        { display: 'Э', value: 'Э' },
        { display: 'Ю', value: 'Ю' },
        { display: 'Я', value: 'Я' },
        { display: 'а', value: 'а' },
        { display: 'б', value: 'б' },
        { display: 'в', value: 'в' },
        { display: 'г', value: 'г' },
        { display: 'д', value: 'д' },
        { display: 'е', value: 'е' },
        { display: 'ж', value: 'ж' },
        { display: 'з', value: 'з' },
        { display: 'ё', value: 'ё' },
        { display: 'и', value: 'и' },
        { display: 'й', value: 'й' },
        { display: 'к', value: 'к' },
        { display: 'л', value: 'л' },
        { display: 'м', value: 'м' },
        { display: 'н', value: 'н' },
        { display: 'о', value: 'о' },
        { display: 'п', value: 'п' },
        { display: 'р', value: 'р' },
        { display: 'с', value: 'с' },
        { display: 'т', value: 'т' },
        { display: 'у', value: 'у' },
        { display: 'ф', value: 'ф' },
        { display: 'х', value: 'х' },
        { display: 'ц', value: 'ц' },
        { display: 'ч', value: 'ч' },
        { display: 'ш', value: 'ш' },
        { display: 'щ', value: 'щ' },
        { display: 'ъ', value: 'ъ' },
        { display: 'ы', value: 'ы' },
        { display: 'ь', value: 'ь' },
        { display: 'э', value: 'э' },
        { display: 'ю', value: 'ю' },
        { display: 'я', value: 'я' }
    ],
    yunani: [
        { display: 'Α', value: 'Α' },
        { display: 'Β', value: 'Β' },
        { display: 'Γ', value: 'Γ' },
        { display: 'Δ', value: 'Δ' },
        { display: 'Ε', value: 'Ε' },
        { display: 'Ζ', value: 'Ζ' },
        { display: 'Η', value: 'Η' },
        { display: 'Θ', value: 'Θ' },
        { display: 'Ι', value: 'Ι' },
        { display: 'Κ', value: 'Κ' },
        { display: 'Λ', value: 'Λ' },
        { display: 'Μ', value: 'Μ' },
        { display: 'Ν', value: 'Ν' },
        { display: 'Ξ', value: 'Ξ' },
        { display: 'Ο', value: 'Ο' },
        { display: 'Π', value: 'Π' },
        { display: 'Ρ', value: 'Ρ' },
        { display: 'Σ', value: 'Σ' },
        { display: 'Τ', value: 'Τ' },
        { display: 'Υ', value: 'Υ' },
        { display: 'Φ', value: 'Φ' },
        { display: 'Χ', value: 'Χ' },
        { display: 'Ψ', value: 'Ψ' },
        { display: 'Ω', value: 'Ω' },
        { display: 'α', value: 'α' },
        { display: 'β', value: 'β' },
        { display: 'γ', value: 'γ' },
        { display: 'δ', value: 'δ' },
        { display: 'ε', value: 'ε' },
        { display: 'ζ', value: 'ζ' },
        { display: 'η', value: 'η' },
        { display: 'θ', value: 'θ' },
        { display: 'ι', value: 'ι' },
        { display: 'κ', value: 'κ' },
        { display: 'λ', value: 'λ' },
        { display: 'μ', value: 'μ' },
        { display: 'ν', value: 'ν' },
        { display: 'ξ', value: 'ξ' },
        { display: 'ο', value: 'ο' },
        { display: 'π', value: 'π' },
        { display: 'ρ', value: 'ρ' },
        { display: 'ς', value: 'ς' },
        { display: 'σ', value: 'σ' },
        { display: 'τ', value: 'τ' },
        { display: 'υ', value: 'υ' },
        { display: 'φ', value: 'φ' },
        { display: 'χ', value: 'χ' },
        { display: 'ψ', value: 'ψ' },
        { display: 'ω', value: 'ω' }
    ],
    eropa: [
        { display: 'À', value: 'À' },
        { display: 'Â', value: 'Â' },
        { display: 'Ç', value: 'Ç' },
        { display: 'É', value: 'É' },
        { display: 'È', value: 'È' },
        { display: 'Î', value: 'Î' },
        { display: 'Ï', value: 'Ï' },
        { display: 'Ô', value: 'Ô' },
        { display: 'Û', value: 'Û' },
        { display: 'Ÿ', value: 'Ÿ' },
        { display: 'Œ', value: 'Œ' },
        { display: 'Æ', value: 'Æ' },
        { display: 'ß', value: 'ß' },
        { display: 'Ä', value: 'Ä' },
        { display: 'Ö', value: 'Ö' },
        { display: 'Ü', value: 'Ü' },
        { display: 'à', value: 'à' },
        { display: 'â', value: 'â' },
        { display: 'ç', value: 'ç' },
        { display: 'é', value: 'é' },
        { display: 'è', value: 'è' },
        { display: 'ê', value: 'ê' },
        { display: 'î', value: 'î' },
        { display: 'ï', value: 'ï' },
        { display: 'ô', value: 'ô' },
        { display: 'û', value: 'û' },
        { display: 'ù', value: 'ù' },
        { display: 'ÿ', value: 'ÿ' },
        { display: 'œ', value: 'œ' },
        { display: 'æ', value: 'æ' },
        { display: 'ä', value: 'ä' },
        { display: 'ö', value: 'ö' },
        { display: 'ü', value: 'ü' }
    ],
    lainnya: [
        { display: '€', value: '€' },
        { display: '£', value: '£' },
        { display: '¥', value: '¥' },
        { display: '₹', value: '₹' },
        { display: '¢', value: '¢' },
        { display: '®', value: '®' },
        { display: '™', value: '™' },
        { display: '‰', value: '‰' }
    ]
};
